config/routes.rb
Swidjit::Application.routes.draw do



  scope 'admin', :module => 'admin' do
    resources :item_preset_tags, :only => [:index, :new, :create, :destroy]
    resources :items, :only => [] do
      collection do
        get :flagged
      end
      put :disable
    end
    resources :users, :only => [:index, :destroy], :as => 'admin_users' do
      put :confirm
    end
  end

  scope ':city_url_name' do

    resource :calendar, :only => [:show] do
      collection do
        get :date, :path => "date/:month/:day/:year", action: :show #, :controller => :calendar, :action => :index
      end
    end

    resources :want_its, :have_its, :thoughts, :links, :events, :collections, :except => :index do
      member do
        put :flag
        get :toggle_active
        get :duplicate
        post :add_visibility_rule
        delete :remove_visibility_rule
        resources :recommendations, :only => :create
        resources :comments, :only => :create
      end
    end

    resources :comments, :only => [:destroy]
    
    resources :collections, :only => [] do
      member do
        post :add_item
      end
    end

    resources :items, :only => [] do
      resources :offers, :only => [:create, :index]
      resources :users, :only => [] do
        resources :offers, :only => :index
      end
    end
    
    resources :suggested_items, :only => [:create,:destroy]
    resources :custom_feeds, :only => [:new, :create]
    resources :custom_feed_subscriptions
    resources :custom_feed_elements, :only => [:new, :create]

    resource :feeds, :only => [] do
      member do
        get 'geo/:tag_name', :action => :geo, :as => 'geo'
        get :nearby
        get :drafts
        get 'recommendations(/:type)', :action => :recommendations, :as => 'recommendations'
        get :suggested_items
        get 'familiar_users(/:type)', :action => :familiar_users, :as => 'familiar_users'
        get :search, :action => :search
        get ':type(/:tag_name)', :action => :index, :as => 'main', :defaults => { :type => :all }
      end
    end

    resources :tags, :only => [] do
      collection do
        get :autocomplete_search
        get :autocomplete_search_geo
      end
    end

    resources :communities, :only => [:new,:create,:show,:index,:destroy,:edit,:update] do
      member do
        post :join
        delete :leave
        resources :community_invitations, :only => :create
      end
      resource :calendar, :only => [:show] do
        collection do
          get :date, :path => "date/:month/:day/:year", action: :show #, :controller => :calendar, :action => :index
        end
      end
    end

    resources :lists, :only => [:show,:create,:destroy,:add_user] do
      member do
        post :add_user
        post :delete_user
      end
    end
    
    resources :custom_feed_elements, :only => [:show,:create,:destroy] do
      member do
        post :add_element
      end
    end
    
    resources :custom_feeds, :only => [:show,:create,:destroy] do
      member do
        post :new
        post :add_element
      end
    end
    
    resources :custom_feed_elements, :only => [:show,:create,:destroy] do
      member do
        post :add
      end
    end
    
    resources :users, :only => [] do
      member do
        get :references
      end
      resources :offers, :only => :index
      resource :calendar, :only => [:show] do
        collection do
          get :date, :path => "date/:month/:day/:year", action: :show #, :controller => :calendar, :action => :index
        end
      end
    end

    resource :calendar, :only => [:show] do
      collection do
        get :date, :path => "date/:month/:day/:year", action: :show #, :controller => :calendar, :action => :index
      end
    end

    resources :delegates, :only => [:create,:destroy]

    resources :bookmarks, :only => [:create,:destroy,:index]

    match 'contact' => 'contact#new', :as => 'contact', :via => :get
    match 'contact' => 'contact#create', :as => 'contact', :via => :post

    resources :rsvps, :only => [:create,:destroy,:index]
    resources :reminders, :only => [:create, :destroy]

    resources :offers, :only => [:show, :destroy] do
      resources :offer_messages, :only => [:create]
    end
  end

  devise_for :users, :controllers => { :registrations => "registrations",
      :omniauth_callbacks => "omniauth_callbacks" }

  get '/users/finish_registration/:hash' => 'users#complete_shadow_user'
  put '/users/finish_registration/:hash' => 'users#submit_shadow_user'

  post '/images/generate' => 'images#generate'

  resources :users, :only => [:edit, :update] do
    member do
      get :visibility_options
      get :suggestions
    end
    resources :geo_tags, :only => [:create, :destroy]
    resources :notifications, :only => :index
    resources :vouches, :only => :create
  end

  match 'pages/:page_name' => 'pages#index', :as => :pages

  # This needs to stay at the bottom such that a user can't override a preset URL
  match '/:display_name', :controller => :users, :action => :show, :as => :profile

  root :to => 'pages#home'

end

app/models/list.rb
class List < ActiveRecord::Base

  belongs_to :user
  has_many :lists_users, :dependent => :destroy
  has_many :users, :through => :lists_users, :uniq => true
  has_many :item_visibility_rules, :as => :visibility, :dependent => :destroy

  attr_accessible :name

  validates_presence_of :name, :user
  validates_uniqueness_of :name, :scope => :user_id

  def users= (*users)
    # Workaround to force callbacks on lists_users
    # TODO: Only remove removed users and only add new users (Prevent removing and then readding)
    self.lists_users.clear
    users.each{|usr| self.users << usr}
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  respond_to :json, :html

  load_and_authorize_resource :only => [:show,:destroy]

  before_filter :load_and_authorize_list, :only => [:add_user,:delete_user]

  def show
    item_type = params[:type] || 'all'
    if %w( events have_its want_its links thoughts ).include? item_type
      item_class = item_type.camelize.singularize.constantize
    else
      params[:type] = 'all'
      item_class = Item
    end
    @feed_items = item_class.where(:user_id => @list.users.collect(&:id)).access_controlled_for(current_user, current_city, current_ability)
    render_paginated_feed :show
  end

  def create
    @list = List.new
    @list.name = params[:list][:name]
    @list.user = current_user
    @list.save
    respond_with @list
  end

  def destroy
    @list.destroy
    redirect_to root_path
  end

  def add_user
    if params[:user_id].present?
      user = User.find(params[:user_id])
    else
      user = User.find_by_display_name(params[:user_display_name])
    end
    if @list.users.include?(user)
      notice = "User already in list #{@list.name}"
      success_val = false
    else
      @list.users << user
      notice = "Successfully added user to #{@list.name}"
      success_val = true
    end
    redirect_to :back
  end

  def delete_user
    user_to_remove = ListsUser.find_by_user_id_and_list_id(params[:user_id], @list.id)
    if user_to_remove.present?
      @list.lists_users.destroy(user_to_remove)
      message = 'Successfully removed user'
    else
      message = 'User not in list'
    end
    respond_to do |f|
      f.json { render :json => {:notice => message, :success => true }}
    end
  end

private
  def load_and_authorize_list
    @list = List.find(params[:id])
    if !can? :manage, @list
      respond_to do |f|
        f.json { render :json => {:notice => 'You are not authorized to do this.', :success => false}}
      end
    end
  end

end

app/views/lists/show.html.haml
.title_heading= @list.name
=link_to 'Delete list', list_path(@list), :confirm => 'Are you sure?', :method => 'delete'

.section-heading
  Users in List
.user_edit
  %ul.tokenized
    %li.add_token
      %input.add-to-list.autocomplete-user{:type=>'text',:placeholder=>'add user'}
    - @list.users.each do |usr|
      %li
        = usr.display_name
        = link_to 'X', delete_user_list_path(:id => @list.id, :user_id => usr.id), :class => 'remove_user_from_list'


%div
  = tabbed_item_types('type')

= render :partial => 'feeds/endless_scroll'

:javascript
  var list_id = #{@list.id};
  $('.remove_user_from_list').live('click',function(){
    var $this_li = $(this).parent('li');
    var url = $(this).attr("href");
    var user_id = url.split('=')[url.split('=').length-1];
    var $users_items = $(".feed input[type='hidden'][name='item_user_id'][value='"+user_id+"']").parent('li');
    $.ajax({
      type: 'POST',
      url: url,
      success: function(data){
        $this_li.remove();
        $users_items.remove();
      }
    });
    return false;
  });
  $(".add-to-list").live("autocompleteselect",function(){
    add_to_list($(this));
  });
  $(".ui-menu-item").live('click',function(){
    add_to_list($(".add-to-list"));
  });
  function add_to_list($self) {
    user_display_name = $self.val();
    var url = base_list_url.replace('/0','/'+list_id) + '/add_user';
    $.ajax({
      type: 'POST',
      url: url,
      data: { user_display_name: user_display_name },
      success: function(data){
        $("span.notice").text(data.notice);
        if(data.success){
          var $new_li = $("<li>").text(user_display_name +' ');
          var remove_url = base_list_url.replace('/0','/'+list_id) + '/delete_user?user_id=' +data.user_id;
          var $remove_link = $("<a>").text('X').addClass('remove_user_from_list').attr('href',remove_url);
          $new_li.append($remove_link);
          $self.closest('li').after($new_li);
          $self.val('');
        }
      },
      error: function(xhr,status,data){
      }
    });
  }